name: DB CD - Apply Migrations

on:
  push:
    branches: [ "main" ]

jobs:
  migrate-prod-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      # Start Cloud SQL Proxy
      - name: Start Cloud SQL Proxy
        run: |
          curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.11.0/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy
          ./cloud-sql-proxy ${{ secrets.CLOUD_SQL_INSTANCE }} --port 3306 &
          sleep 10

      - name: Install Flyway
        run: |
          wget -qO- https://download.redgate.com/maven/release/com/redgate/flyway/flyway-commandline/10.10.0/flyway-commandline-10.10.0-linux-x64.tar.gz | tar xvz && sudo ln -s `pwd`/flyway-10.10.0/flyway /usr/local/bin

      # Run Flyway migrations
      - name: Run Flyway migrate (production)
        run: |
          flyway \
            -url="jdbc:mysql://127.0.0.1:3306/${{ secrets.DB_NAME }}" \
            -user="${{ secrets.DB_USER }}" \
            -password="${{ secrets.DB_PASSWORD }}" \
            -locations="filesystem:db/migrations" \
            baseline
