name: DB CD - Apply Migrations

on:
  push:
    branches: [ "main" ]

jobs:
  migrate-prod-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Start Cloud SQL Proxy (Docker)
        run: |
          docker run -d \
            --name cloud-sql-proxy \
            -p 3306:3306 \
            gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0 \
            ${{ secrets.CLOUD_SQL_INSTANCE }} --port 3306

          echo "Waiting for Cloud SQL Proxy..."
          sleep 15

      - name: Flyway BASELINE (RUN ONCE)
        run: |
          docker run --rm \
            --network host \
            -v ${{ github.workspace }}/db/migrations:/flyway/sql \
            flyway/flyway:10 \
            -url=jdbc:mysql://127.0.0.1:3306/${{ secrets.DB_NAME }} \
            -user=${{ secrets.DB_USER }} \
            -password=${{ secrets.DB_PASSWORD }} \
            baseline
